[package]
name = "wallet_kit_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.39", features = ["full", "fold"] }
proc-macro2 = "1.0.66"