[all]
exclude-files = [
    "profile/bindings/*",
    "profile/tests/test_generated_bindings.rs",
]
verbose = true
all-features = true
workspace = true
timeout = "1800s"
out = ["xml"]
force-clean = false
