[package]
name = "profile"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = { version = "1.0.108", features = ["preserve_order"] }
serde_with = { version = "3.0.0", features = ["hex"] }

serde_repr = "0.1.17"
strum = { version = "0.25.0", features = ["derive"] }
hierarchical_deterministic = { path = "../hierarchical_deterministic" }
wallet_kit_common = { path = "../wallet_kit_common" }
enum-iterator = "1.4.1"
radix-engine-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "038ddee8b0f57aa90e36375c69946c4eb634efeb", features = [
    "serde",
] }
thiserror = "1.0.50"
chrono = { version = "0.4.31", features = ["serde"] }
uuid = { version = "1.5.0", features = ["v4", "serde"] }
radix-engine-toolkit = { git = "https://github.com/radixdlt/radix-engine-toolkit", rev = "927b0c88dcc62325edf7c6279ee3f84f26a6eadc" }
radix-engine-toolkit-json = { git = "https://github.com/radixdlt/radix-engine-toolkit", rev = "927b0c88dcc62325edf7c6279ee3f84f26a6eadc" }
nutype = { version = "0.4.0", features = ["serde"] }
transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "038ddee8b0f57aa90e36375c69946c4eb634efeb", features = [
    "serde",
] }
enum-as-inner = "0.6.0"
identified_vec = { version = "0.1.8", features = ["serde", "id_prim"] }
url = { version = "2.5.0", features = ["serde"] }
